<?php

declare(strict_types=1);

/*
 * PreToolUse guard for Edit / Write / NotebookEdit.
 *
 * Refuses writes to files that are generated, secret, or otherwise not the
 * real source of truth. Exit code 2 blocks the tool call and hands the
 * message on stderr back to Claude so it can pick the correct file instead.
 */

$input = json_decode((string) stream_get_contents(STDIN), true);

if (! is_array($input)) {
    exit(0);
}

$path = $input['tool_input']['file_path'] ?? '';

if (! is_string($path) || $path === '') {
    exit(0);
}

$normalise = static fn (string $p): string => str_replace('\\', '/', $p);

$path = $normalise($path);
$root = rtrim($normalise((string) ($input['cwd'] ?? getcwd())), '/');

// Reduce to a path relative to the project root so the rules below stay readable.
$relative = str_starts_with(strtolower($path), strtolower($root).'/')
    ? substr($path, strlen($root) + 1)
    : ltrim($path, '/');

$blockedFiles = [
    'composer.lock' => 'Run `composer require` / `composer update` instead — the lock file is generated.',
    'package-lock.json' => 'Run `npm install <pkg>` instead — the lock file is generated.',
    'pnpm-lock.yaml' => 'Run the package manager instead — the lock file is generated.',
    'yarn.lock' => 'Run the package manager instead — the lock file is generated.',
];

if (isset($blockedFiles[$relative])) {
    fwrite(STDERR, "Blocked write to {$relative}\n\n".$blockedFiles[$relative]);
    exit(2);
}

$blockedPatterns = [
    '#^resources/js/(actions|routes|wayfinder)/#i' => <<<'TXT'
        Wayfinder regenerates resources/js/{actions,routes,wayfinder}/ on every Vite
        build, and all three are gitignored — an edit here is silently overwritten
        the next time anything builds.

        To change the generated output, change its source: the route definition in
        routes/web.php or the controller signature in app/Http/Controllers/.
        TXT,

    '#^\.env(\.|$)#i' => <<<'TXT'
        .env holds real credentials and is gitignored. Edit .env.example instead and
        ask the user to copy any secret across by hand.
        TXT,

    '#^public/build/#i' => 'public/build/ is Vite output. Edit the source under resources/ and rebuild.',

    '#^bootstrap/ssr/#i' => 'bootstrap/ssr/ is generated by `npm run build:ssr`. Edit resources/js/ssr.tsx instead.',

    '#^vendor/#i' => 'vendor/ is Composer-managed. Do not patch dependencies in place.',

    '#^node_modules/#i' => 'node_modules/ is npm-managed. Do not patch dependencies in place.',
];

foreach ($blockedPatterns as $pattern => $reason) {
    if (preg_match($pattern, $relative) === 1) {
        fwrite(STDERR, "Blocked write to {$relative}\n\n".trim($reason));
        exit(2);
    }
}

exit(0);
